version: '3.8'
services:
  dev-db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: mandy
      POSTGRES_PASSWORD: rlaalswl12!
      POSTGRES_DB: todolist
    networks:
      - nesttodolist
networks:
  nesttodolist: